### PR TITLE
Created the view only member attendance page

### PR DESCRIPTION
**Pull request by FrankM-7**
“As an APPSO member, I want to be able to see all the events that I have attended and not attended.”

 

Acceptance Criteria:

Only members can access  this page.

Layout isn't messy

### CODE REVIEW

**Comment by Daniul** [comment]
Nice! Reviewing code right now.

**Comment by Daniul** [comment]
Creating review app for pull request...

**Comment by Daniul** [comment]
Looks good! no errors were presents, tests passed via CI/CDs via GitHub Actions. Feel free to merge with main.

**Comment by dillonl33** [comment]
Looks good to me

**Pull request merged**
