### PR TITLE
Google OAuth Implementation and Database Rework.

### PR DESCRIPTION
**Pull request by Daniul**
Acceptance Criteria for Google OAuth:

Acceptance Criteria:

OAuth successfully implemented to protect users' username and password during log-in

There is little to no risk of users' credentials being stolen

Redirects to google to ask user to login to google account

ONLY TAMU ACCOUNTS CAN LOGIN VIA GOOGLE

### CODE REVIEW

**Comment by Daniul** [comment]
Looks like it has completed all CI/CD RSpec tests.

**Comment by FrankM-7** [comment]
Looks great!

**Comment by margin25** [comment]
fabulous!

**Comment by nathanpat7** [comment]
Looks good to me! :)

**Pull request merged**
